const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    name: "Green Top",
    price: 25,
    image: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    company: "Levis",
    description: `This Green Top by Levis is crafted from high-quality fabric to ensure comfort and style. Perfect for casual outings, it combines a flattering fit with modern design. Pair it with jeans or shorts for a relaxed yet trendy look.`,
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recEHmzvupvT8ZONH",
    name: "Floral Top",
    price: 60,
    image: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    company: "Vero Moda",
    description: `This Floral Top from Vero Moda brings elegance to your office wardrobe. The delicate floral pattern adds charm, while the breathable fabric keeps you comfortable throughout the day. Ideal for professional yet stylish appearances.`,
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "rec5NBwZ5zCD9nfF0",
    name: "Floral Dress",
    price: 50,
    image: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    company: "Only",
    description: `A charming Floral Dress from Only, perfect for casual gatherings or brunch with friends. Its flowy design ensures ease of movement, while the soft fabric keeps you comfortable all day. Pair with sandals for a complete look.`,
    category: "Casual",
    amount: 1,
    stock: 4,
  },
  {
    id: "recd1jIVIEChmiwhe",
    name: "Red Dress",
    price: 70,
    image: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    company: "Vero Moda",
    description: `This Red Dress by Vero Moda makes a bold statement. Featuring playful polka dots and a flattering silhouette, it’s perfect for office events or evening gatherings. Style it with heels for an elegant touch.`,
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoM2MyHJGHLVi5l",
    name: "Striped Sweater",
    price: 80,
    image: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    company: "Only",
    description: `Stay cozy with this Striped Sweater from Only. Ideal for office or casual wear, its warm knit fabric and stylish design make it perfect for chilly days. Pair with trousers or skirts for a chic look.`,
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recotY5Nh00DQFdkm",
    name: "Yellow Trouser",
    price: 20,
    image: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    company: "Only",
    description: `These Yellow Trousers from Only are designed for casual comfort. Made with breathable material, they’re perfect for relaxed outings or sports activities. Combine with a simple top for a bright, stylish ensemble.`,
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "rec1Ntk7siEEW9ha1",
    name: "White Top",
    price: 40,
    image: "https://i.ibb.co/qBcrsJg/white-vest.png",
    company: "Only",
    description: `A classic White Top from Only that is versatile for every wardrobe. Lightweight and breathable, this top is perfect for casual or semi-formal looks. Pair with jeans, skirts, or trousers for effortless style.`,
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "recNZ0koOqEmilmoz",
    name: "Pink Sweatshirt",
    price: 90,
    image: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    company: "Levis",
    description: `This Pink Sweatshirt by Levis is comfortable and stylish. Perfect for office casuals or weekend wear, its soft fabric keeps you warm, while the vibrant pink adds a fun touch to your outfit.`,
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "recrfxv3EwpvJwvjq",
    name: "Brown Coat",
    price: 100,
    image: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    company: "Only",
    description: `This Brown Coat from Only is a timeless piece for your wardrobe. Its structured design and premium fabric make it ideal for office wear or evening outings. Layer over dresses or trousers for an elegant look.`,
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoW8ecgjtKx2Sj2",
    name: "Grey Jacket",
    price: 20,
    image: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    company: "Vero Moda",
    description: `A stylish Grey Jacket by Vero Moda, perfect for casual outings. Its durable material and modern cut make it a great layering piece. Wear it over tops or dresses for an added edge to your outfit.`,
    category: "Casual",
    amount: 1,
    stock: 5,
  },
];

export default data;
